name: Run News AI Bot

on:
  schedule:
    - cron: '0 9 * * *'  # ይህ ማለት በየቀኑ ጠዋት በራሱ ሰዓት ይነሳል ማለት ነው
  workflow_dispatch:      # ይህ ደግሞ በፈለግክ ጊዜ በእጅህ Run ለማድረግ ይረዳል

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-node-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests groq

      - name: Run script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python news_bot.py
